//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Class.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessoryStock
    {
        public string BatchID { get; set; }
        public string AccessoryID { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> SuppleirID { get; set; }
    
        public virtual Accessory Accessory { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
