//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Class.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accessory()
        {
            this.AccessoryStock = new HashSet<AccessoryStock>();
            this.ProductAccessories = new HashSet<ProductAccessories>();
        }
    
        public string AccessoryID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public decimal Width { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public byte[] Image { get; set; }
        public decimal Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessoryStock> AccessoryStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAccessories> ProductAccessories { get; set; }
    }
}
