//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Class.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.Fabric = new HashSet<Fabric>();
        }
    
        public string Name { get; set; }
        public int AccountedQuantity { get; set; }
        public int ActualQuantity { get; set; }
        public Nullable<int> Difference { get; set; }
        public Nullable<double> DifferencePercentage { get; set; }
        public int ID { get; set; }
        public string RollID { get; set; }
        public Nullable<int> IdMovementMaterial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fabric> Fabric { get; set; }
        public virtual FabricStock FabricStock { get; set; }
        public virtual MaterialMovement MaterialMovement { get; set; }
    }
}
