//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Class.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBase1Entities : DbContext
    {
        public DataBase1Entities()
            : base("name=DataBase1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accessory> Accessories { get; set; }
        public virtual DbSet<Accessories_TheProduct> Accessories_TheProduct { get; set; }
        public virtual DbSet<Cloth> Clothes { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Ordered_Products> Ordered_Products { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TheProduct> TheProducts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Warehouse_Accessories> Warehouse_Accessories { get; set; }
        public virtual DbSet<Warehouse_Cloth> Warehouse_Cloth { get; set; }
    }
}
