//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Class.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSpecificationHistory
    {
        public int HistoryID { get; set; }
        public string ProductID { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Length { get; set; }
        public string ChangeReason { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
