//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Class.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAccessories
    {
        public string AccessoryID { get; set; }
        public string ProductID { get; set; }
        public string Placement { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Rotation { get; set; }
        public int Quantity { get; set; }
    
        public virtual Accessory Accessory { get; set; }
        public virtual Product Product { get; set; }
    }
}
