//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Class.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_Cloth
    {
        public int Рулон { get; set; }
        public string Артикул_ткани { get; set; }
        public double Ширина { get; set; }
        public double Длина { get; set; }
    
        public virtual Cloth Cloth { get; set; }
    }
}
